#ifndef VERSION_HPP
#define VERSION_HPP

#define APP_NAME    "@PROJECT_NAME@"
#define APP_VERSION "@PROJECT_VERSION@"

#define VER_MAJOR @PROJECT_VERSION_MAJOR@
#define VER_MINOR @PROJECT_VERSION_MINOR@
#define VER_PATCH @PROJECT_VERSION_PATCH@
#define VER_TWEAK @PROJECT_VERSION_TWEAK@

#endif
